spring:
  application:
    name: homepilot-ai
  config:
    import: optional:classpath:application-secrets.yaml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
